name: test
on:
  push:
    branches-ignore:
      - main

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v5
      - id: set-modules
        run: echo "modules=[$(find -type f -name go.mod -printf '"%h",')]" >> $GITHUB_OUTPUT

  lint-and-test:
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.modules }}/go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.4
          working-directory: ${{ matrix.modules }}
      - name: Verify dependencies
        run: cd ${{ matrix.modules }} && go mod verify
      - name: Run tests
        run: cd ${{ matrix.modules }} && go test ./...
