name: test
on:
  push:
    branches-ignore:
      - main

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: set-modules
        run: echo "modules=[$(find -type f -name go.mod -printf '"%h",')]" >> $GITHUB_OUTPUT

  lint-and-test:
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ${{ matrix.modules }}/go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.11.3
          working-directory: ${{ matrix.modules }}
      - name: Verify dependencies
        run: cd ${{ matrix.modules }} && go mod verify
      - name: Run tests
        run: cd ${{ matrix.modules }} && go test ./...
